# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: 'Install dagger'
description: 'Install dagger'
inputs: {}
outputs: {}
runs:
  using: "composite"
  steps:
    - name: Install dagger-cue
      shell: bash
      run: |
        mkdir -p "$HOME/.local"
        cd "$HOME/.local"
        curl -L https://dl.dagger.io/dagger-cue/install.sh | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Initialize project
      shell: bash
      run: |
        dagger-cue project init
        dagger-cue project update
